export const PRODUCTS = [
  { id: 1, name: "Poco C65", category: "Budget", price: 7499, description: "Budget phone with MediaTek Helio G85, 50MP AI camera, and 5000mAh battery." },
  { id: 2, name: "Realme C55", category: "Budget", price: 9999, description: "Entry-level phone featuring Mini Capsule notification notch, 64MP camera, and 33W charging." },
  { id: 3, name: "Redmi 13C 5G", category: "Budget", price: 10499, description: "Affordable 5G phone with MediaTek Dimensity 6100+ and 90Hz smooth display." },
  { id: 4, name: "Moto G34 5G", category: "Budget", price: 11999, description: "Clean Stock Android 5G phone powered by Snapdragon 695 and 120Hz display." },
  { id: 5, name: "Redmi 14C 5G", category: "Budget", price: 11999, description: "Sleek 4nm Snapdragon 4 Gen 2 powered phone with huge 120Hz display." },
  { id: 6, name: "Samsung Galaxy M15 5G", category: "Budget", price: 12999, description: "Massive 6000mAh battery with Super AMOLED 90Hz display and 50MP triple camera." },
  { id: 7, name: "Realme NARZO N65 5G", category: "Budget", price: 12499, description: "Dimensity 6300 5G processor with IP54 water resistance and air gesture controls." },
  { id: 8, name: "Vivo T3x 5G", category: "Budget", price: 13499, description: "Snapdragon 6 Gen 1 processor with 6000mAh battery and dual stereo speakers." },
  { id: 9, name: "Redmi A7 Pro", category: "Budget", price: 13499, description: "Big 6.9-inch HD+ display, 6300mAh battery, and IP52 splash resistance." },
  { id: 10, name: "iQOO Z9x 5G", category: "Budget", price: 14499, description: "Snapdragon 6 Gen 1 chip with 44W fast charging and IP64 dust/water resistance." },

  { id: 11, name: "CMF Phone 1 by Nothing", category: "Mid-Range", price: 15999, description: "Unique modular design with removable back covers, Dimensity 7300, and Super AMOLED." },
  { id: 12, name: "Realme 12+ 5G", category: "Mid-Range", price: 18999, description: "Premium vegan leather back, Sony LYT-600 OIS camera, and 67W fast charging." },
  { id: 13, name: "Samsung Galaxy M17 5G", category: "Mid-Range", price: 17999, description: "Exynos 1330 processor, 50MP OIS triple camera, and Gorilla Glass Victus protection." },
  { id: 14, name: "OnePlus Nord CE 4 Lite 5G", category: "Mid-Range", price: 19999, description: "120Hz AMOLED display, 80W SUPERVOOC charging, and Sony OIS primary lens." },
  { id: 15, name: "Poco X6 Pro 5G", category: "Mid-Range", price: 23999, description: "Performance beast with Dimensity 8300-Ultra, 1.5K AMOLED, and WildBoost gaming." },
  { id: 16, name: "Motorola Edge 50 Fusion", category: "Mid-Range", price: 22999, description: "Curved 144Hz pOLED display, IP68 underwater protection, and Sony LYT-700C OIS camera." },
  { id: 17, name: "iQOO Z9 5G", category: "Mid-Range", price: 19999, description: "Dimensity 7200 chip with 4K recording, 120Hz AMOLED, and Sony OIS sensor." },
  { id: 18, name: "Nothing Phone (2a)", category: "Mid-Range", price: 23999, description: "Iconic Glyph lighting interface, clean Nothing OS, Dimensity 7200 Pro, and 50MP dual cameras." },
  { id: 19, name: "OnePlus Nord 4 5G", category: "Mid-Range", price: 29999, description: "All-metal unibody design, Snapdragon 7+ Gen 3, and 100W fast charging." },
  { id: 20, name: "Vivo V30e 5G", category: "Mid-Range", price: 27999, description: "Slim 3D curved display with Aura Light portrait camera system and 5500mAh battery." },

  { id: 21, name: "Realme GT 6T", category: "Premium Mid-Range", price: 30999, description: "Snapdragon 7+ Gen 3 with ultra-bright 6000-nit LTPO display and 120W charging." },
  { id: 22, name: "Motorola Edge 50 Pro", category: "Premium Mid-Range", price: 31999, description: "Pantone validated camera & display, 125W turbo charging, 50W wireless charging, and IP68." },
  { id: 23, name: "Samsung Galaxy A55 5G", category: "Premium Mid-Range", price: 35999, description: "Metal frame, IP67 dust/water resistance, Knox Vault security, and Nightography camera." },
  { id: 24, name: "Samsung Galaxy A56 5G", category: "Premium Mid-Range", price: 38999, description: "Super AMOLED 120Hz display, Exynos 1480, long OS update commitment, and sleek Olive finish." },
  { id: 25, name: "iQOO Neo 9 Pro", category: "Premium Mid-Range", price: 34999, description: "Snapdragon 8 Gen 2 flaghsip chip, Supercomputing Q1 gaming chip, and 120W FlashCharge." },
  { id: 26, name: "Xiaomi 14 Civi", category: "Premium Mid-Range", price: 39999, description: "Leica professional triple camera system, quad-curved display, and Snapdragon 8s Gen 3." },
  { id: 27, name: "Google Pixel 8a", category: "Premium Mid-Range", price: 41999, description: "Tensor G3 processor with Google AI features, 7 years of OS updates, and Best Take photo tools." },
  { id: 28, name: "Google Pixel 9a 5G", category: "Premium Mid-Range", price: 42180, description: "Google Tensor G4 AI chip, 8GB RAM, stellar low-light camera, and 7 years of software support." },
  { id: 29, name: "OnePlus 12R", category: "Premium Mid-Range", price: 39999, description: "Snapdragon 8 Gen 2, 4th gen LTPO 120Hz display, and massive 5500mAh battery with 100W." },
  { id: 30, name: "Vivo V40 Pro", category: "Premium Mid-Range", price: 49999, description: "ZEISS professional optics portrait lenses, Dimensity 9200+ chip, and IP68 rating." },

  { id: 31, name: "iQOO 12 5G", category: "Flagship", price: 52999, description: "Snapdragon 8 Gen 3 flagship processor, 144Hz LTPO AMOLED, and 64MP periscope telephoto." },
  { id: 32, name: "OnePlus 12", category: "Flagship", price: 64999, description: "4th Gen Hasselblad camera for mobile, Snapdragon 8 Gen 3, 2K display, and 50W wireless charging." },
  { id: 33, name: "Samsung Galaxy S24", category: "Flagship", price: 62999, description: "Compact AI flagship with Galaxy AI features, Armor Aluminum frame, and Dynamic AMOLED 2X." },
  { id: 34, name: "Samsung Galaxy S24 FE", category: "Flagship", price: 54999, description: "Fan Edition with full Galaxy AI suite, 50MP triple camera, and vibrant 6.7-inch display." },
  { id: 35, name: "iPhone 15", category: "Flagship", price: 65999, description: "Dynamic Island, 48MP main camera, A16 Bionic chip, and USB-C port with durable color-infused glass." },
  { id: 36, name: "iPhone 16", category: "Flagship", price: 79900, description: "Apple Intelligence ready, A18 chip, Action button, Camera Control slider, and 48MP Fusion camera." },
  { id: 37, name: "iPhone 16 Plus", category: "Flagship", price: 89900, description: "Larger 6.7-inch display, extended battery life, A18 chip, and Apple Intelligence features." },
  { id: 38, name: "Google Pixel 9", category: "Flagship", price: 79999, description: "Google Tensor G4 chip, 12GB RAM, Gemini Nano on-device AI, and redesigned camera bar." },
  { id: 39, name: "Vivo X100 Pro", category: "Flagship", price: 89999, description: "ZEISS 1-inch main camera sensor, APO Floating Telephoto lens, and Dimensity 9300 flagship chip." },
  { id: 40, name: "OnePlus 13 5G", category: "Flagship", price: 69999, description: "Snapdragon 8 Elite chip, Hasselblad master camera system, and IP69 water & dust resistance." },

  { id: 41, name: "iPhone 16 Pro", category: "Ultra Flagship", price: 119900, description: "Grade 5 Titanium design, A18 Pro chip, 4K 120 fps Dolby Vision video, and 5x Telephoto lens." },
  { id: 42, name: "iPhone 16 Pro Max", category: "Ultra Flagship", price: 144900, description: "Massive 6.9-inch Super Retina XDR display, best iPhone battery life ever, and A18 Pro chip." },
  { id: 43, name: "Samsung Galaxy S24 Ultra 5G", category: "Ultra Flagship", price: 109999, description: "Titanium frame, built-in S Pen, 200MP camera, Quad Tele System, and Galaxy AI suite." },
  { id: 44, name: "Samsung Galaxy S25 Ultra 5G", category: "Ultra Flagship", price: 129999, description: "Titanium chassis, Snapdragon 8 Elite Gen 5, ProVisual Engine 200MP camera, and One UI 7." },
  { id: 45, name: "Samsung Galaxy S26 Ultra 5G", category: "Ultra Flagship", price: 139999, description: "Slimmest Ultra design, Armor Aluminum frame, 200MP ProVisual AI sensor, and One UI 8.5." },
  { id: 46, name: "Google Pixel 9 Pro XL", category: "Ultra Flagship", price: 124999, description: "Super Actua display, Tensor G4 with 16GB RAM, Gemini Advanced, and 50MP triple camera system." },
  { id: 47, name: "Xiaomi 14 Ultra", category: "Ultra Flagship", price: 99999, description: "Leica quad camera system with 1-inch variable aperture main sensor and Photography Kit support." },
  { id: 48, name: "Samsung Galaxy Z Flip6 5G", category: "Foldable", price: 109999, description: "Compact flip phone with FlexWindow cover screen, 50MP main camera, and Auto Zoom feature." },
  { id: 49, name: "Samsung Galaxy Z Fold6 5G", category: "Foldable", price: 164999, description: "Book-style foldable with massive 7.6-inch inner screen, S Pen support, and dual-app multitasking." },
  { id: 50, name: "Samsung Galaxy Z Fold7 5G", category: "Foldable", price: 186999, description: "Ultra-slim Jetblack dual-screen foldable, 12GB RAM / 512GB storage, and advanced multitasking." },
  { id: 51, name: "OnePlus Open", category: "Foldable", price: 139999, description: "Lightweight foldable with Open Canvas multi-window OS, Hasselblad cameras, and minimal crease." },
  { id: 52, name: "Google Pixel 9 Pro Fold", category: "Foldable", price: 172999, description: "Google's thinnest foldable with massive 8-inch Super Actua Flex inner display and Gemini AI." }
];